services:
  comfyui:
    build: .
    user: root
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8188:8188"
    volumes:
      - "./models:/app/models"
      - "./input:/app/input"
      - "./output/temp:/app/output/temp"
      - "./output:/app/output"
      - "./user:/app/user"
      - "./custom_nodes:/app/custom_nodes"
